Fix (deploy-app): added 'do', 'if', 'fi', 'done' structure to the 'Verify Kubernetes permissions' step.

diff --git a/.github/workflows/deploy-app.yaml b/.github/workflows/deploy-app.yaml
--- a/.github/workflows/deploy-app.yaml
+++ b/.github/workflows/deploy-app.yaml
@@ -57,6 +57,20 @@ jobs:
                     "create services" \
                     "patch services"
                     "get endpointslices.discovery.k8s.io"
+                  do
+                    verb="${permission%% *}"
+                    resource="${permission#* }"
+
+                    result="$(
+                      kubectl auth can-i "$verb" "$resource" \
+                        --namespace "$KUBERNETES_NAMESPACE"
+                    )"
+
+                    if [ "$result" != "yes" ]; then
+                      echo "Missing permission: $verb $resource"
+                      exit 1
+                    fi
+                  done
 
             - name: Validate APP_SECRET
               env:
